name: same_boat
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.0-7.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: 1.14.1
  firebase_database: 9.0.11
  hooks_riverpod: 1.0.3
  built_value: ^8.1.0
  built_collection: ^5.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.10
  built_value_generator: ^8.2.0

flutter:
  uses-material-design: true

        
    
    
                                      